src/Entity/Name.php
<?php

namespace App\Entity;

use App\Repository\NameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ORM\Entity(repositoryClass=NameRepository::class)
 */
class Name
{
    const GENDER_MALE = 'M';
    const GENDER_FEMALE = 'F';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"front_end"})
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"front_end"})
     */
    private ?string $name = null;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private ?string $gender = null;

    /**
     * @ORM\OneToMany(targetEntity=Year::class, mappedBy="name", orphanRemoval=true)
     * @ORM\OrderBy({"year"="DESC"})
     * @Groups({"front_end"})
     */
    private Collection $years;

    public function __construct()
    {
        $this->years = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @Groups({"front_end"})
     * @SerializedName("gender")
     */
    public function getGenderHuman(): string
    {
        return $this->getGender() == self::GENDER_MALE ? 'Male' : 'Female';
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection|Year[]
     */
    public function getYears(): Collection
    {
        return $this->years;
    }

    public function addYear(Year $year): self
    {
        if (!$this->years->contains($year)) {
            $this->years[] = $year;
            $year->setName($this);
        }

        return $this;
    }

    public function removeYear(Year $year): self
    {
        if ($this->years->contains($year)) {
            $this->years->removeElement($year);
            // set the owning side to null (unless already changed)
            if ($year->getName() === $this) {
                $year->setName(null);
            }
        }

        return $this;
    }
}

src/Entity/Year.php
<?php

namespace App\Entity;

use App\Repository\YearRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ORM\Entity(repositoryClass=YearRepository::class)
 */
class Year
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"front_end"})
     */
    private ?int $year = null;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"front_end"})
     */
    private ?int $count = null;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $rank = null;

    /**
     * @ORM\ManyToOne(targetEntity=Name::class, inversedBy="years")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Name $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(?int $count): self
    {
        $this->count = $count;

        return $this;
    }

    /**
     * @Groups({"front_end"})
     * @SerializedName("rank")
     */
    public function getRankWithoutZero(): ?int
    {
        if($this->rank == 0) return 6000;
        return $this->rank;
    }

    public function getRank(): ?int
    {
        return $this->rank;
    }

    public function setRank(?int $rank): self
    {
        $this->rank = $rank;

        return $this;
    }

    public function getName(): ?Name
    {
        return $this->name;
    }

    public function setName(?Name $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Controller/AbstractRestController.php
<?php

namespace App\Controller;

use FOS\RestBundle\Context\Context;
use FOS\RestBundle\Controller\AbstractFOSRestController;
use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\ConstraintViolationList;

class AbstractRestController extends AbstractFOSRestController
{

    /**
     * @param array<array>|object $data
     * @param array<string> $groups
     */
    public function createView($data, array $groups = ['front_end']): View
    {
        $context = new Context();
        $view = $this->view($data);
        $context->setGroups($groups);
        $view->setContext($context);
        return $view;
    }

    protected function createValidationErrorsResponse(ConstraintViolationList $validationErrors, int $statusCode = null): Response
    {
        $view = $this->createView( $validationErrors);
        $view
            ->setStatusCode($statusCode ?? 400)
            ->setFormat('json');

        return $this->handleView($view);
    }


}

src/Controller/ApiController.php
<?php

namespace App\Controller;

use App\Entity\Name;
use App\Repository\NameRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ApiController
 * @Route("/api", name="api")
 */
class ApiController extends AbstractRestController
{

    /**
     * @Route("/search/{term}", methods={"GET"}, format="json")
     */
    public function index(string $term, NameRepository $repository): Response
    {
        $result = $repository->findForSearch($term);
        return $this->handleView($this->createView($result));
    }

    /**
     * @Route("/details/{id}", methods={"GET"}, format="json")
     */
    public function details(Name $name): Response
    {
        return $this->handleView($this->createView($name));
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Name;
use App\Repository\YearRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    const LATEST_YEAR = 2022;

    /**
     * @Route("/")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig');
    }

    /**
     * @Route("/top-names/{gender}")
     */
    public function topNames(YearRepository $repo, string $gender): Response
    {
        $top = [];

        $years = range(self::LATEST_YEAR, 1996, -1);

        foreach ($years as $year){
            $top[$gender][$year] = $repo->getTop($gender, $year);
        }

        return $this->render('default/top.html.twig', [
            'top' => $top
        ]);
    }

    /**
     * @Route("/details/{id}")
     */
    public function name(Name $name): Response
    {
        $topYear = null;

        foreach ($name->getYears() as $year){
            if($year->getRank() > 0) {
                if (!$topYear) $topYear = $year;
                if ($year->getRank() < $topYear->getRank()) $topYear = $year;
            }
        }

        return $this->render('default/name.html.twig', [
            'name' => $name,
            'topYear' => ($topYear ? $topYear->getYear(): null)
        ]);
    }

    /**
     * @Route("/names-for-letter/{letter}")
     * @Route("/names-for-letter")
     */
    public function namesForLetter(YearRepository $repo, string $letter='a'): Response
    {
        $year = self::LATEST_YEAR;
        $letters = range('a', 'z');
        if(!in_array($letter, $letters)) throw $this->createNotFoundException('Not a letter');

        $genders = [Name::GENDER_MALE, Name::GENDER_FEMALE];
        $names = [];
        foreach ($genders as $gender) {
            $names[$gender] = $repo->getTopForLetter($letter, $year, $gender);
        }

        return $this->render('default/name_for_letter.html.twig', [
            'result' => $names,
            'year' => $year,
            'currentLetter' => $letter,
            'letters' => $letters,
        ]);
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>{% block title %}Baby names!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid max-width">
            <header>
                <span class="menu-toggle">Menu</span>
                <nav>
                    <a href="{{ path('app_default_index') }}" class="mr-2">Graph of names</a>
                    <a href="{{ path('app_default_topnames', {gender: 'm'}) }}" class="mr-2">Top Male names</a>
                    <a href="{{ path('app_default_topnames', {gender: 'f'}) }}" class="mr-2">Top Female names</a>
                    <a href="{{ path('app_default_namesforletter') }}" class="mr-2">Top names per letter</a>
                </nav>
            </header>
        </div>
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid max-width">
        <p class="mt-3">Use the text box below to search for names, these will appear in rank order for each year on the graph</p>
        <div id="root"></div>
    </div>
{% endblock %}

templates/default/name.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid max-width">
        <div class="row name-details">
            <div class="col-12">
                <h2>{{ name.name }}</h2>
                <p>Rankings for {{ name.name }} for {{ name.genderHuman }} babies for each year, the bold year is the highest ranking year.</p>

                <table class="table">
                    <tr>
                        <th>Year</th>
                        <th>Rank</th>
                        <th>Count</th>
                    </tr>
                    {% for year in name.years %}
                        <tr {{ topYear == year.year ? 'class="top"' }}>
                            <td>{{ year.year }}</td>
                            <td>{{ year.rank }}</td>
                            <td>{{ year.count|number_format }}</td>
                        </tr>
                    {% endfor %}
                </table>

            </div>
        </div>
    </div>
{% endblock %}

templates/default/name_for_letter.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid max-width">
        <div class="row">
            <div class="col-12">
                <h3 class="mt-3">Top 20 names for {{ year }} starting with letter "{{ currentLetter|upper }}"</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <ul class="list-inline mt-3">
                    {% for letter in letters %}
                        <li class="list-inline-item">
                            <a href="{{ path('app_default_namesforletter', {letter: letter}) }}" class="">{{ letter|upper }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="row">
            {% for gender,names in result %}
                <div class="col-12 col-md-6">
                    <h3 class="mt-3">{{ gender|lower == 'm' ? 'Male' : 'Female' }} names</h3>
                    {% include 'partial/name-table.html.twig' %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/default/top.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container-fluid max-width">

    {% for gender,years in top %}
        <div class="row">
            <div class="col-12">
                <h3 class="mt-3">Top 50 {{ gender == 'm' ? 'Male' : 'Female' }} names</h3>
            </div>
        </div>
        <div class="row">
            {% for year,names in years %}
                <div class="col-12 col-md-3">
                    <h4 class="mt-3">{{ year }}</h4>
                    {% include 'partial/name-table.html.twig' %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}

</div>
{% endblock %}

templates/partial/name-table.html.twig
<table class="table">
    <tr>
        <th>Rank</th>
        <th>Count</th>
        <th>Name</th>
    </tr>
    {% for name in names %}
        <tr>
            <td>{{ name.rank }}</td>
            <td>{{ name.count }}</td>
            <td>{{ name.name }}</td>
        </tr>
    {% endfor %}
</table>